repos:

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.0
  hooks:
  - id: clang-format
    types_or: [c++, c, cuda]

- repo: https://github.com/google/yapf
  rev: v0.40.2
  hooks:
  - id: yapf

- repo: https://github.com/pre-commit/mirrors-jshint
  rev: v2.13.6
  hooks:
  - id: jshint
