repos:

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v16.0.0
  hooks:
  - id: clang-format
    types_or: [c++, c, cuda]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.11
  hooks:
  - id: ruff-check
    args: [--fix]
  - id: ruff-format

- repo: https://github.com/biomejs/pre-commit
  rev: v2.1.2
  hooks:
  - id: biome-check
