# This file is automatically generated by setuptools-scm
# It is committed to the repository to allow Dependabot to resolve dependencies
# without building the package. During normal builds, this file is overwritten.
__version__ = version = "0.0.0"
__version_tuple__ = version_tuple = (0, 0, 0)
